### ISSUE TITLE
Pool throws NPE panic on client dial

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-sdk-go#470]
* encountered within https://github.com/nspcc-dev/neofs-s3-gw/issues/794

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa65b44]

goroutine 1 [running]:
github.com/nspcc-dev/neofs-api-go/v2/rpc/grpc.(*Client).Init(0x0, {{0xf555b5, 0x1e}, {0xf3fc90, 0xb}, 0x1}, {0xc0009e0cd0, 0x1, 0xc0009980b0?})
        github.com/nspcc-dev/neofs-api-go/v2@v2.14.0/rpc/grpc/init.go:81 +0x2e4
github.com/nspcc-dev/neofs-api-go/v2/rpc/client.(*Client).initGRPC(0xc000906070, {{0xf555b5, 0x1e}, {0xf3fc90, 0xb}, 0x1}, 0xc0009980b0)
        github.com/nspcc-dev/neofs-api-go/v2@v2.14.0/rpc/client/init.go:75 +0xf8
github.com/nspcc-dev/neofs-api-go/v2/rpc/client.(*Client).Init(0x7f689d708338?, {{0xf555b5, 0x1e}, {0xf3fc90, 0xb}, 0x1}, {0xc0009e0eb0, 0x1, 0x18?})
        github.com/nspcc-dev/neofs-api-go/v2@v2.14.0/rpc/client/init.go:48 +0xfd
github.com/nspcc-dev/neofs-api-go/v2/rpc/client.SendUnary(0x46469a?, {{0xf555b5, 0x1e}, {0xf3fc90, 0xb}, 0x1}, {0x12a2c90, 0xc00056c078}, {0x12a2d08, 0xc00056c0d8}, ...)
        github.com/nspcc-dev/neofs-api-go/v2@v2.14.0/rpc/client/flows.go:15 +0x8a
github.com/nspcc-dev/neofs-api-go/v2/rpc.NetworkInfo(0x8?, 0xe47e60?, {0xc0009e0eb0, 0x1, 0x1})
        github.com/nspcc-dev/neofs-api-go/v2@v2.14.0/rpc/netmap.go:41 +0x126
github.com/nspcc-dev/neofs-sdk-go/client.(*Client).NetworkInfo.func1()
        github.com/nspcc-dev/neofs-sdk-go@v1.0.0-rc.9.0.20230606101007-79edfa63bbc9/client/netmap.go:142 +0x78
github.com/nspcc-dev/neofs-sdk-go/client.(*contextCall).processCall.func1()
        github.com/nspcc-dev/neofs-sdk-go@v1.0.0-rc.9.0.20230606101007-79edfa63bbc9/client/common.go:252 +0x25
github.com/nspcc-dev/neofs-sdk-go/client.(*contextCall).writeRequest(0xc00090abd0)
        github.com/nspcc-dev/neofs-sdk-go@v1.0.0-rc.9.0.20230606101007-79edfa63bbc9/client/common.go:160 +0x187
github.com/nspcc-dev/neofs-sdk-go/client.(*contextCall).processCall(0xc00090abd0)
        github.com/nspcc-dev/neofs-sdk-go@v1.0.0-rc.9.0.20230606101007-79edfa63bbc9/client/common.go:257 +0x85
github.com/nspcc-dev/neofs-sdk-go/client.(*Client).NetworkInfo(0xc000906050, {0x12a81a8?, 0xc000906000}, {{{0x0?, 0xe40ac0?, 0x19e2d00?}}})
        github.com/nspcc-dev/neofs-sdk-go@v1.0.0-rc.9.0.20230606101007-79edfa63bbc9/client/netmap.go:163 +0x247
github.com/nspcc-dev/neofs-sdk-go/pool.(*clientWrapper).networkInfo(0xc0002ee6c0, {0x12a81a8, 0xc000906000}, {})
        github.com/nspcc-dev/neofs-sdk-go@v1.0.0-rc.9.0.20230606101007-79edfa63bbc9/pool/pool.go:566 +0x88
github.com/nspcc-dev/neofs-sdk-go/pool.initSessionForDuration({0x12a81a8, 0xc000906000}, 0xc0009e16d0, {0x12b5ca0, 0xc0002ee6c0}, 0x64, {0x12a7d00, 0xc0009026c0})
        github.com/nspcc-dev/neofs-sdk-go@v1.0.0-rc.9.0.20230606101007-79edfa63bbc9/pool/pool.go:1726 +0x7e
github.com/nspcc-dev/neofs-sdk-go/pool.(*Pool).Dial(0xc00090a120, {0x12a81a8, 0xc000906000})
        github.com/nspcc-dev/neofs-sdk-go@v1.0.0-rc.9.0.20230606101007-79edfa63bbc9/pool/pool.go:1475 +0x9ec
```

**Comment by cthulhu-rider** [comment]
`Client.Dial` problem was fixed by 79d4b97db942e9165f1d5aabe83b62fbed03eba7
