### ISSUE TITLE
Nil pointer exception using this script

### ISSUE THREAD

**Issue by amlwwalker** [nspcc-dev/neofs-sdk-go#477]
@cthulhu-rider has been helping me work out some issues, and suggested I post this here as I get a nil pointer when the url port is incorrect.
```go
func TestSlicerRelay(t *testing.T) {
	const endpoint = "grpcs://st4.t5.fs.neo.org:8082"
	const strCnr = "8C6PxKix8BAW8gPpZqigmJwZdmMjHYUbv1pnrGn4bCY9"
	payload := strings.NewReader("Hello, world!")
	ctx := context.Background()

	gateAcc, err := wallet.NewAccount()
	require.NoError(t, err)

	usrWallet, err := wallet.NewWalletFromFile("/Users/alex.walker/go/src/github.com/amlwwalker/greenfinch.react/wallets/wallet.json")
	require.NoError(t, err)

	usrAcc := usrWallet.Accounts[0]

	err = usrAcc.Decrypt("password", keys.NEP2ScryptParams())
	require.NoError(t, err)

	var gateSigner neofscrypto.Signer = neofsecdsa.SignerRFC6979(gateAcc.PrivateKey().PrivateKey)
	var usrSigner neofscrypto.Signer = neofsecdsa.Signer(usrAcc.PrivateKey().PrivateKey)

	var cnr cid.ID
	require.NoError(t, cnr.DecodeString(strCnr))

	var prmInit client.PrmInit

	c, err := client.New(prmInit)
	require.NoError(t, err)

	var prmDial client.PrmDial
	prmDial.SetTimeout(1 * time.Minute)
	prmDial.SetServerURI(endpoint)

	require.NoError(t, c.Dial(prmDial))

	t.Cleanup(func() {
		_ = c.Close()
	})

	netInfo, err := c.NetworkInfo(ctx, client.PrmNetworkInfo{})
	require.NoError(t, err)

	var opts slicer.Options
	opts.SetObjectPayloadLimit(netInfo.MaxObjectSize())
	opts.SetCurrentNeoFSEpoch(netInfo.CurrentEpoch())
	if !netInfo.HomomorphicHashingDisabled() {
		opts.CalculateHomomorphicChecksum()
	}

	var sessionToken session.Object
	sessionToken.SetAuthKey(gateSigner.Public())
	sessionToken.SetID(uuid.New())
	sessionToken.SetIat(netInfo.CurrentEpoch())
	sessionToken.SetNbf(netInfo.CurrentEpoch())
	sessionToken.SetExp(netInfo.CurrentEpoch() + 100) // or particular exp value
	sessionToken.BindContainer(cnr)
	sessionToken.ForVerb(session.VerbObjectPut)

	require.NoError(t, sessionToken.Sign(usrSigner))

	objWriter := &objectWriter{
		context: ctx,
		client:  c,
		session: &sessionToken,
	}

	_slicer := slicer.NewSession(gateSigner, cnr, sessionToken, objWriter, opts)

	id, err := _slicer.Slice(payload, object.AttributeFileName, "alex-testing-something")
	require.NoError(t, err)
	log.Println("object:", id)
}
```

error
```
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x453ea86]

goroutine 19 [running]:
testing.tRunner.func1.2({0x4b4f820, 0x5690770})
	/usr/local/go/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1392 +0x39f
panic({0x4b4f820, 0x5690770})
	/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/nspcc-dev/neofs-sdk-go/crypto.(*Signature).Calculate(0xc0000d96f0, {0x0, 0x0}, {0x0?, 0x4adaab8?, 0xc0000d9700?})
	/Users/alex.walker/go/pkg/mod/github.com/nspcc-dev/neofs-sdk-go@v1.0.0-rc.9/crypto/signature.go:61 +0x46
github.com/nspcc-dev/neofs-sdk-go/client.signServiceMessagePart({0x0, 0x0}, {0x4e42090?, 0x0?}, 0xc0000d9850)
	/Users/alex.walker/go/pkg/mod/github.com/nspcc-dev/neofs-sdk-go@v1.0.0-rc.9/client/sign.go:209 +0xda
github.com/nspcc-dev/neofs-sdk-go/client.signServiceMessage({0x0, 0x0}, {0x4be66a0?, 0xc00000e438})
	/Users/alex.walker/go/pkg/mod/github.com/nspcc-dev/neofs-sdk-go@v1.0.0-rc.9/client/sign.go:175 +0x392
github.com/nspcc-dev/neofs-sdk-go/client.(*contextCall).writeRequest(0xc00036c090)
	/Users/alex.walker/go/pkg/mod/github.com/nspcc-dev/neofs-sdk-go@v1.0.0-rc.9/client/common.go:154 +0xbc
github.com/nspcc-dev/neofs-sdk-go/client.(*contextCall).processCall(0xc00036c090)
	/Users/alex.walker/go/pkg/mod/github.com/nspcc-dev/neofs-sdk-go@v1.0.0-rc.9/client/common.go:257 +0x79
github.com/nspcc-dev/neofs-sdk-go/client.(*Client).NetworkInfo(0xc0001a80f0, {0x4e478d0?, 0xc00019e008}, {{{0x0?, 0x0?, 0x0?}}})
	/Users/alex.walker/go/pkg/mod/github.com/nspcc-dev/neofs-sdk-go@v1.0.0-rc.9/client/netmap.go:163 +0x227
github.com/amlwwalker/greenfinch.react/pkg/manager.TestSlicerRelay(0xc00029aea0)
	/Users/alex.walker/go/src/github.com/amlwwalker/greenfinch.react/pkg/manager/writer_test.go:60 +0x3bd
testing.tRunner(0xc00029aea0, 0x4d679b8)
	/usr/local/go/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1486 +0x35f
	
```
specifically here `netInfo, err := c.NetworkInfo(ctx, client.PrmNetworkInfo{})`

**Comment by cthulhu-rider** [comment]
* version used https://github.com/nspcc-dev/neofs-sdk-go/releases/tag/v1.0.0-rc.9

guess this is caused by `SetDefaultSigner` which was required in rc-9 and no longer needed in latest revision. Code snippet was originally written on 1300860c8ce5cd37e20528dc591e190836891fa9. So i guess there won't be problem in rc-10.

@amlwwalker u can try to add
```go
var prmInit client.PrmInit
prmInit.SetDefaultSigner(gateSigner) // this
```
and check there is no more NPE

**Comment by amlwwalker** [comment]
by the looks of things this fix will not be in the rc10 version @roman-khimov ? 
how would I adjust this for chunked payloads so I can show progress?

**Comment by roman-khimov** [comment]
We're at RC11 now and if you're using writer-based slicer you have all control and visibility into the process.

**Comment by amlwwalker** [comment]
is the above an example of writer based slicer @roman-khimov - sorry it moves faster than I can so if you could show me a snippet that would be a massive help just trying to get over the hump of this wallet connect stuff finally 😁

**Comment by amlwwalker** [comment]
@roman-khimov looking here - it seems i either create a payload writer that can chunk, or i create a slicer - but i cant see how i create a slicer that can handle chunks?
https://pkg.go.dev/github.com/nspcc-dev/neofs-sdk-go@v1.0.0-rc.11/object/slicer

**Comment by amlwwalker** [comment]
here
```
	contID, err := wait.ContainerPut(ctx, cont, usrSigner, prmContPut)
```
we use the user's wallet address. I guess its not possible to create containers like we are doing with putting the object - that is using the gateKey as an intermediary thereby not ever having to expose the user's private key or with containers will we _always_ have to create/manage containers knowing the private key/password?

**Comment by roman-khimov** [comment]
This signer is only needed for the `Put` operation, that is to create the container. And it needs to be of a specific type IIRC. But the signature can be computed outside of the SDK. The waiter just polls for the container with `Get`, but this doesn't require `signer` in fact.
